// Curated brand → ownership database.
//
// `indian` is true when the brand's ultimate owner is an Indian company.
// Brand ownership changes over time (acquisitions, demergers), so every entry
// should be easy to audit: keep the owner name explicit and add a `note` when
// the history is surprising (e.g. Thums Up was Indian, now Coca-Cola).
//
// Categories are used to suggest Swadeshi alternatives.

const I = (owner, category, names, note) => ({ owner, country: 'India', indian: true, category, names, note });
const F = (owner, country, category, names, note) => ({ owner, country, indian: false, category, names, note });

const GROUPS = [
  // ---------------- Dairy ----------------
  I('Gujarat Co-operative Milk Marketing Federation', 'dairy', ['Amul']),
  I('Mother Dairy (NDDB)', 'dairy', ['Mother Dairy', 'Dhara', 'Safal']),
  I('Karnataka Milk Federation', 'dairy', ['Nandini']),
  I('Tamil Nadu Co-operative Milk Producers Federation', 'dairy', ['Aavin']),
  I('Punjab State Co-operative Milk Producers Federation', 'dairy', ['Verka']),
  I('Parag Milk Foods', 'dairy', ['Gowardhan', 'Go Cheese', 'Avvatar']),
  I('Hatsun Agro Product', 'dairy', ['Arun Ice Creams', 'Arokya', 'Hatsun']),
  I('Heritage Foods', 'dairy', ['Heritage']),
  I('Milky Mist Dairy', 'dairy', ['Milky Mist']),
  I('Vadilal Industries', 'dairy', ['Vadilal']),

  // ---------------- Packaged food & snacks ----------------
  I('Britannia Industries (Wadia Group)', 'biscuits', ['Britannia', 'Good Day', 'Marie Gold', 'NutriChoice', 'Tiger', 'Milk Bikis', 'Treat', 'Little Hearts', '50-50']),
  I('Parle Products', 'biscuits', ['Parle', 'Parle-G', 'Monaco', 'Krackjack', 'Hide & Seek', 'Melody', 'Kismi', 'Poppins', 'Mango Bite']),
  I('ITC Limited', 'packaged-food', ['Aashirvaad', 'Sunfeast', 'Dark Fantasy', 'Bingo', 'Yippee', 'B Natural', 'Candyman', 'Sunrise', 'Kitchens of India']),
  I('Haldiram\'s', 'snacks', ['Haldiram', 'Haldirams', 'Haldiram\'s']),
  I('Bikaji Foods International', 'snacks', ['Bikaji']),
  I('Bikanervala Foods', 'snacks', ['Bikanervala', 'Bikano']),
  I('Balaji Wafers', 'snacks', ['Balaji Wafers', 'Balaji']),
  I('Prataap Snacks', 'snacks', ['Yellow Diamond']),
  I('RP-Sanjiv Goenka Group', 'snacks', ['Too Yumm']),
  I('Tata Consumer Products', 'packaged-food', ['Tata Sampann', 'Tata Salt', 'Ching\'s Secret', 'Smith & Jones', 'Soulfull', 'Organic India', 'Tata Gluco Plus'], 'Ching\'s Secret / Smith & Jones (Capital Foods) and Organic India were acquired by Tata in 2024.'),
  I('MDH (Mahashian Di Hatti)', 'spices', ['MDH']),
  I('Everest Food Products', 'spices', ['Everest']),
  I('DS Group', 'spices', ['Catch', 'Pass Pass', 'Pulse']),
  I('Shree Mahila Griha Udyog', 'packaged-food', ['Lijjat']),
  I('iD Fresh Food', 'packaged-food', ['iD Fresh', 'iD']),
  I('Patanjali Ayurved', 'packaged-food', ['Patanjali', 'Nutrela', 'Ruchi Gold']),
  I('Zydus Wellness', 'health-drinks', ['Complan', 'Glucon-D', 'Sugar Free', 'Nutralite', 'Sampriti'], 'Zydus acquired these brands from Heinz India in 2019.'),
  I('Hamdard Laboratories (India)', 'beverages', ['Rooh Afza', 'Safi', 'Hamdard']),
  I('Dabur India', 'beverages', ['Real', 'Real Activ']),

  // ---------------- Beverages ----------------
  I('Tata Consumer Products', 'tea-coffee', ['Tata Tea', 'Tetley', 'Tata Coffee', 'Tata Coffee Grand', 'Eight O\'Clock', 'Tata Copper+', 'Himalayan'], 'Tetley (UK origin) has been owned by the Tata group since 2000.'),
  I('Wagh Bakri Tea Group', 'tea-coffee', ['Wagh Bakri']),
  I('Society Tea (Hasmukhrai & Co.)', 'tea-coffee', ['Society Tea']),
  I('Parle Agro', 'beverages', ['Frooti', 'Appy', 'Appy Fizz', 'Smoodh', 'Bailley', 'Bailey']),
  I('Bisleri International', 'water', ['Bisleri', 'Vedica']),
  I('Hector Beverages', 'beverages', ['Paper Boat']),
  I('Reliance Consumer Products', 'beverages', ['Campa', 'Campa Cola', 'Independence'], 'Campa Cola is a heritage Indian brand revived by Reliance in 2023.'),

  // ---------------- Personal care & home care ----------------
  I('Dabur India', 'personal-care', ['Dabur', 'Vatika', 'Hajmola', 'Odomos', 'Odonil', 'Dabur Red', 'Meswak', 'Babool', 'Fem']),
  I('Himalaya Wellness', 'personal-care', ['Himalaya']),
  I('Marico', 'personal-care', ['Parachute', 'Saffola', 'Nihar', 'Set Wet', 'Livon', 'Beardo', 'Hair & Care', 'Kaya']),
  I('Godrej Consumer Products', 'personal-care', ['Cinthol', 'Godrej No.1', 'Godrej Expert', 'Good Knight', 'HIT', 'Ezee', 'Godrej Aer', 'Godrej Protekt']),
  I('Emami', 'personal-care', ['Boroplus', 'Navratna', 'Zandu', 'Kesh King', 'Emami', 'Fair and Handsome', 'Smart and Handsome', 'Mentho Plus']),
  I('ITC Limited', 'personal-care', ['Fiama', 'Vivel', 'Savlon', 'Engage', 'Superia', 'Nimyle', 'Mangaldeep', 'Classmate'], 'ITC acquired Savlon and Shower to Shower (India) from Johnson & Johnson in 2015.'),
  I('Wipro Consumer Care', 'personal-care', ['Santoor', 'Chandrika', 'Glucovita', 'Safewash']),
  I('Jyothy Labs', 'home-care', ['Ujala', 'Exo', 'Henko', 'Maxo', 'Margo', 'Pril', 'Neem']),
  I('Nirma', 'home-care', ['Nirma']),
  I('RSPL Group', 'home-care', ['Ghadi']),
  I('Vicco Laboratories', 'personal-care', ['Vicco', 'Vicco Turmeric', 'Vicco Vajradanti']),
  I('GD Pharmaceuticals', 'personal-care', ['Boroline']),
  I('Cholayil', 'personal-care', ['Medimix', 'Cuticura']),
  I('Amrutanjan Healthcare', 'personal-care', ['Amrutanjan']),
  I('Honasa Consumer', 'personal-care', ['Mamaearth', 'The Derma Co', 'Aqualogica', 'Dr. Sheth\'s', 'BBlunt']),
  I('Biotique', 'personal-care', ['Biotique']),
  I('Lotus Herbals', 'personal-care', ['Lotus Herbals', 'Lotus Professional']),
  I('Nykaa (FSN E-Commerce)', 'personal-care', ['Nykaa', 'Kay Beauty']),
  I('Sugar Cosmetics (Vellvette Lifestyle)', 'personal-care', ['Sugar Cosmetics']),
  I('Khadi and Village Industries Commission', 'personal-care', ['Khadi', 'Khadi India']),
  I('Pidilite Industries', 'home-care', ['Fevicol', 'Fevikwik', 'M-Seal', 'Dr. Fixit', 'Fevistik']),

  // ---------------- Electronics & appliances ----------------
  I('Imagine Marketing', 'electronics', ['boAt'], 'Indian brand; many products are still manufactured abroad, so check "Country of Origin".'),
  I('Nexxbase Marketing', 'electronics', ['Noise']),
  I('Fire-Boltt (Indya Dot Com)', 'electronics', ['Fire-Boltt', 'Fire Boltt']),
  I('Lava International', 'electronics', ['Lava']),
  I('Micromax Informatics', 'electronics', ['Micromax']),
  I('Havells India', 'appliances', ['Havells', 'Lloyd', 'Standard', 'Reo']),
  I('Bajaj Electricals', 'appliances', ['Bajaj Electricals', 'Morphy Richards'], 'Bajaj Electricals holds the Morphy Richards licence for India.'),
  I('Crompton Greaves Consumer Electricals', 'appliances', ['Crompton', 'Butterfly']),
  I('Usha International (Shriram Group)', 'appliances', ['Usha']),
  I('Orient Electric (CK Birla Group)', 'appliances', ['Orient Electric', 'Orient']),
  I('V-Guard Industries', 'appliances', ['V-Guard', 'V Guard']),
  I('Polycab India', 'appliances', ['Polycab']),
  I('TTK Prestige', 'kitchenware', ['Prestige', 'Judge']),
  I('Hawkins Cookers', 'kitchenware', ['Hawkins', 'Futura']),
  I('Stovekraft', 'kitchenware', ['Pigeon', 'Gilma']),
  I('Godrej & Boyce', 'appliances', ['Godrej Appliances', 'Godrej Interio', 'Godrej Security']),
  I('Voltas (Tata Group)', 'appliances', ['Voltas', 'Voltas Beko']),
  I('Blue Star', 'appliances', ['Blue Star']),
  I('IFB Industries', 'appliances', ['IFB']),
  I('Borosil', 'kitchenware', ['Borosil', 'Larah']),
  I('Cello World', 'kitchenware', ['Cello']),
  I('Hamilton Housewares', 'kitchenware', ['Milton', 'Treo']),

  // ---------------- Fashion, footwear, lifestyle ----------------
  I('Titan Company (Tata Group)', 'lifestyle', ['Titan', 'Fastrack', 'Tanishq', 'Sonata', 'Titan Eye+', 'Raga', 'Skinn']),
  I('Raymond', 'apparel', ['Raymond', 'Park Avenue', 'ColorPlus', 'Parx']),
  I('Fabindia', 'apparel', ['Fabindia']),
  I('Vedant Fashions', 'apparel', ['Manyavar', 'Mohey']),
  I('Aditya Birla Fashion & Retail', 'apparel', ['Peter England', 'Louis Philippe', 'Allen Solly', 'Van Heusen', 'Pantaloons'], 'ABFRL owns these brands for India.'),
  I('Relaxo Footwears', 'footwear', ['Relaxo', 'Sparx', 'Flite', 'Bahamas']),
  I('Campus Activewear', 'footwear', ['Campus']),
  I('Liberty Shoes', 'footwear', ['Liberty']),
  I('Khadim India', 'footwear', ['Khadim']),
  I('Paragon Polymer Products', 'footwear', ['Paragon']),
  I('VKC Group', 'footwear', ['VKC Pride', 'VKC']),
  I('Asian Paints', 'paints', ['Asian Paints', 'Apcolite', 'Royale', 'Tractor Emulsion']),
  I('Berger Paints India', 'paints', ['Berger']),

  // ---------------- Automobiles ----------------
  I('Tata Motors', 'automobiles', ['Tata Motors', 'Jaguar', 'Land Rover'], 'Jaguar Land Rover has been owned by Tata Motors since 2008.'),
  I('Mahindra & Mahindra', 'automobiles', ['Mahindra', 'Scorpio', 'Thar', 'XUV']),
  I('Bajaj Auto', 'automobiles', ['Bajaj', 'Pulsar', 'Chetak']),
  I('Hero MotoCorp', 'automobiles', ['Hero', 'Splendor', 'Vida']),
  I('TVS Motor Company', 'automobiles', ['TVS', 'Apache', 'Jupiter']),
  I('Eicher Motors', 'automobiles', ['Royal Enfield']),
  I('Ola Electric', 'automobiles', ['Ola Electric']),
  I('Ather Energy', 'automobiles', ['Ather']),

  // ================= Foreign-owned =================
  F('Unilever (Hindustan Unilever)', 'United Kingdom', 'personal-care', ['Hindustan Unilever', 'HUL', 'Lux', 'Lifebuoy', 'Dove', 'Pears', 'Pond\'s', 'Ponds', 'Glow & Lovely', 'Lakme', 'Clinic Plus', 'Sunsilk', 'TRESemme', 'Close-Up', 'Closeup', 'Pepsodent', 'Vaseline', 'Axe', 'Rexona', 'Hamam', 'Liril', 'Indulekha']),
  F('Unilever (Hindustan Unilever)', 'United Kingdom', 'home-care', ['Surf Excel', 'Rin', 'Wheel', 'Vim', 'Domex', 'Comfort', 'Sunlight']),
  F('Unilever (Hindustan Unilever)', 'United Kingdom', 'packaged-food', ['Kissan', 'Knorr', 'Annapurna', 'Hellmann\'s']),
  F('Unilever (Hindustan Unilever)', 'United Kingdom', 'tea-coffee', ['Brooke Bond', 'Red Label', 'Taj Mahal', 'Taaza', 'Bru']),
  F('Unilever (Hindustan Unilever)', 'United Kingdom', 'health-drinks', ['Horlicks', 'Boost'], 'HUL acquired Horlicks and Boost from GSK in 2020.'),
  F('Magnum Ice Cream Company (Kwality Wall\'s)', 'Netherlands', 'dairy', ['Kwality Wall\'s', 'Kwality Walls', 'Cornetto', 'Magnum']),
  F('Procter & Gamble', 'United States', 'personal-care', ['Head & Shoulders', 'Pantene', 'Gillette', 'Oral-B', 'Whisper', 'Pampers', 'Olay', 'Old Spice']),
  F('Procter & Gamble', 'United States', 'home-care', ['Ariel', 'Tide', 'Ambi Pur']),
  F('Procter & Gamble', 'United States', 'healthcare', ['Vicks']),
  F('Colgate-Palmolive', 'United States', 'personal-care', ['Colgate', 'Palmolive']),
  F('Nestlé', 'Switzerland', 'packaged-food', ['Nestle', 'Maggi', 'KitKat', 'Kit Kat', 'Munch', 'Milkybar', 'Cerelac', 'Lactogen', 'Nestle Everyday', 'Polo', 'Bar-One']),
  F('Nestlé', 'Switzerland', 'tea-coffee', ['Nescafe', 'Nescafé']),
  F('Mondelez International', 'United States', 'chocolates', ['Cadbury', 'Dairy Milk', 'Silk', '5 Star', 'Five Star', 'Perk', 'Gems', 'Fuse', 'Eclairs', 'Oreo', 'Bournvita', 'Tang', 'Halls'], 'Cadbury (UK origin) has been owned by Kraft/Mondelez since 2010.'),
  F('Mars', 'United States', 'chocolates', ['Snickers', 'Mars', 'Bounty', 'Galaxy', 'M&M\'s', 'Pedigree', 'Whiskas']),
  F('Ferrero', 'Italy', 'chocolates', ['Ferrero Rocher', 'Nutella', 'Kinder', 'Tic Tac']),
  F('Lotte', 'South Korea', 'chocolates', ['Lotte', 'Choco Pie']),
  F('Lotte', 'South Korea', 'dairy', ['Havmor'], 'Havmor ice cream has been owned by Lotte since 2017.'),
  F('Kellanova', 'United States', 'packaged-food', ['Kellogg\'s', 'Kelloggs', 'Chocos', 'Pringles']),
  F('Orkla', 'Norway', 'packaged-food', ['MTR', 'Eastern'], 'MTR Foods has been owned by Orkla since 2007.'),
  F('PepsiCo', 'United States', 'snacks', ['Lay\'s', 'Lays', 'Kurkure', 'Uncle Chipps', 'Doritos', 'Cheetos', 'Quaker']),
  F('PepsiCo', 'United States', 'beverages', ['Pepsi', '7Up', '7 Up', 'Mountain Dew', 'Mirinda', 'Tropicana', 'Slice', 'Gatorade', 'Sting', 'Aquafina']),
  F('The Coca-Cola Company', 'United States', 'beverages', ['Coca-Cola', 'Coca Cola', 'Coke', 'Thums Up', 'Limca', 'Maaza', 'Sprite', 'Fanta', 'Kinley', 'Minute Maid', 'Charged'], 'Thums Up, Limca and Maaza were Indian (Parle) brands sold to Coca-Cola in 1993.'),
  F('Danone', 'France', 'dairy', ['Danone', 'Protinex', 'Aptamil']),
  F('Reckitt', 'United Kingdom', 'home-care', ['Dettol', 'Harpic', 'Lizol', 'Mortein', 'Colin', 'Vanish']),
  F('Reckitt', 'United Kingdom', 'healthcare', ['Durex', 'Veet', 'Strepsils', 'Disprin', 'Moov', 'Gaviscon']),
  F('Kenvue (Johnson & Johnson)', 'United States', 'personal-care', ['Johnson\'s', 'Johnsons Baby', 'Neutrogena', 'Clean & Clear', 'Stayfree', 'Listerine', 'Band-Aid']),
  F('L\'Oréal', 'France', 'personal-care', ['L\'Oreal', 'Loreal', 'Garnier', 'Maybelline', 'CeraVe']),
  F('Beiersdorf', 'Germany', 'personal-care', ['Nivea']),
  F('Estée Lauder', 'United States', 'personal-care', ['Estee Lauder', 'Clinique', 'MAC']),
  F('Henkel', 'Germany', 'home-care', ['Schwarzkopf', 'Loctite']),
  F('Samsung', 'South Korea', 'electronics', ['Samsung']),
  F('LG Electronics', 'South Korea', 'electronics', ['LG']),
  F('Apple', 'United States', 'electronics', ['Apple', 'iPhone', 'iPad', 'MacBook', 'AirPods']),
  F('Xiaomi', 'China', 'electronics', ['Xiaomi', 'Redmi', 'Mi', 'Poco']),
  F('BBK / Oppo group', 'China', 'electronics', ['Oppo', 'Realme', 'OnePlus']),
  F('Vivo', 'China', 'electronics', ['Vivo', 'iQOO']),
  F('Transsion', 'China', 'electronics', ['Tecno', 'Infinix', 'itel']),
  F('Lenovo', 'China', 'electronics', ['Lenovo', 'Motorola']),
  F('Haier', 'China', 'appliances', ['Haier']),
  F('Sony', 'Japan', 'electronics', ['Sony', 'PlayStation']),
  F('Panasonic', 'Japan', 'appliances', ['Panasonic']),
  F('Whirlpool', 'United States', 'appliances', ['Whirlpool']),
  F('Philips', 'Netherlands', 'appliances', ['Philips']),
  F('HP', 'United States', 'electronics', ['HP', 'Hewlett-Packard']),
  F('Dell', 'United States', 'electronics', ['Dell']),
  F('Nike', 'United States', 'footwear', ['Nike', 'Jordan']),
  F('Adidas', 'Germany', 'footwear', ['Adidas', 'Reebok'], 'Reebok India is operated under licence; brand is foreign-owned.'),
  F('Puma', 'Germany', 'footwear', ['Puma']),
  F('Bata Corporation', 'Switzerland', 'footwear', ['Bata', 'Hush Puppies', 'Power']),
  F('Suzuki Motor Corporation', 'Japan', 'automobiles', ['Maruti Suzuki', 'Maruti', 'Suzuki'], 'Maruti Suzuki India is majority-owned by Suzuki (Japan) though cars are made in India.'),
  F('Hyundai Motor Company', 'South Korea', 'automobiles', ['Hyundai', 'Kia']),
  F('Toyota', 'Japan', 'automobiles', ['Toyota']),
  F('Honda', 'Japan', 'automobiles', ['Honda']),
];

export const BRANDS = GROUPS.flatMap((g) =>
  g.names.map((name) => ({
    name,
    owner: g.owner,
    country: g.country,
    indian: g.indian,
    category: g.category,
    note: g.note || null,
  })),
);

// Brand names that are also everyday words. They are only trusted when they
// come from a structured "brand" field, never when spotted in free OCR text.
export const AMBIGUOUS_NAMES = new Set([
  'real', 'hit', 'hero', 'catch', 'pulse', 'treat', 'tiger', 'silk', 'fuse', 'charged', 'eastern',
  'judge', 'orient', 'royale', 'mars', 'slice', 'comfort', 'sunlight', 'polo', 'halls', 'gems',
  'perk', 'kaya', 'fem', 'neem', 'standard', 'campus', 'liberty', 'power', 'independence', 'safal',
  'id', 'apple', 'jordan', 'raga', 'skinn', 'treo', 'futura', 'mi', 'himalayan', 'appy', 'reo',
  'sugar free', 'khadi', 'parx', 'lloyd', 'flite', 'bahamas', 'thar', 'xuv', 'apache', 'jupiter',
  'chetak', 'vida', 'aer', 'engage', 'superia', 'sunrise', 'everyday', 'nestle everyday', 'fair and handsome',
  'tide', 'wheel', 'rin', 'vim', 'axe', 'boost', 'coke', 'sting', 'eclairs', 'lux', 'dove', 'taaza',
  'sprite', 'margo', 'ezee', 'expert', 'emami', 'little hearts', 'bailey', 'bailley', 'go cheese',
  'pril', 'exo', 'maxo', 'sparx', 'chocos', 'gilma', 'pigeon', 'butterfly', 'larah',
  'lava', 'noise', 'sonata', 'paragon',
]);

export const CATEGORY_LABELS = {
  dairy: 'Dairy & ice cream',
  biscuits: 'Biscuits',
  'packaged-food': 'Packaged food',
  snacks: 'Snacks',
  spices: 'Spices',
  'health-drinks': 'Health drinks',
  beverages: 'Beverages',
  'tea-coffee': 'Tea & coffee',
  water: 'Packaged water',
  chocolates: 'Chocolates & confectionery',
  'personal-care': 'Personal care',
  'home-care': 'Home care',
  healthcare: 'Healthcare',
  electronics: 'Electronics',
  appliances: 'Appliances',
  kitchenware: 'Kitchenware',
  lifestyle: 'Watches & jewellery',
  apparel: 'Apparel',
  footwear: 'Footwear',
  paints: 'Paints',
  automobiles: 'Automobiles',
};

// Categories that are close enough to share alternatives.
export const RELATED_CATEGORIES = {
  chocolates: ['biscuits', 'snacks'],
  healthcare: ['personal-care'],
  water: ['beverages'],
  'health-drinks': ['beverages', 'dairy'],
};
